export const politicalParties = [
  { label: "Peoples Democratic Party (PDP)", value: "PDP" },
  { label: "All Progressives Congress (APC)", value: "APC" },
  { label: "Social Democratic Party (SDP)", value: "SDP" },
  { label: "Labour Party (LP)", value: "LP" },
  { label: "All Progressives Grand Alliance (APGA)", value: "APGA" },
  { label: "Action Democratic Party (ADP)", value: "ADP" },
  { label: "Alliance for New Nigeria (ANN)", value: "ANN" },
  { label: "Allied Peoples Movement (APM)", value: "APM" },
  { label: "Accord Party (AP)", value: "AP" },
  { label: "African Action Congress (AAC)", value: "AAC" },
  { label: "Action Alliance (AA)", value: "AA" },
  { label: "African Democratic Congress (ADC)", value: "ADC" },
  { label: "Boat Peoples Congress (BPC)", value: "BPC" },
  { label: "Democratic Alternative (DA)", value: "DA" },
  { label: "Democratic Peoples Congress (DPC)", value: "DPC" },
  { label: "Democratic Socialist Movement (DSM)", value: "DSM" },
  { label: "Freedom and Justice Party (FJP)", value: "FJP" },
  { label: "Fresh Democratic Party (FDP)", value: "FDP" },
];
export const assembly = [
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "9", value: "9" },
  { label: "10", value: "10" },
];
