export const peopleData = [
  {
    id: "1",
    firstName: "Robert",
    lastName: "Wolfkisser",
    phoneNumber: "0813456789",
    email: "rob_wolf@gmail.com",
    group: "Alpha",
    level: "Level 4",
    status: "Online",
    erpStatus: "Activated",
  },
  {
    id: "2",
    firstName: "Alice",
    lastName: "Moonlight",
    phoneNumber: "0821234567",
    email: "alice_moon@gmail.com",
    group: "Beta",
    level: "Level 3",
    status: "Offline",
    erpStatus: "Deactivated",
  },
  {
    id: "3",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0839876543",
    email: "john_doe@gmail.com",
    group: "Gamma",
    level: "Level 2",
    status: "Online",
    erpStatus: "Activated",
  },
  {
    id: "4",
    firstName: "Emma",
    lastName: "Skywalker",
    phoneNumber: "0845678901",
    email: "emma_sky@gmail.com",
    group: "Delta",
    level: "Level 1",
    status: "Offline",
    erpStatus: "Deactivated",
  },
  {
    id: "5",
    firstName: "Michael",
    lastName: "Thunderbolt",
    phoneNumber: "0852345678",
    email: "michael_thunder@gmail.com",
    group: "Epsilon",
    level: "Level 5",
    status: "Online",
    erpStatus: "Activated",
  },
  {
    id: "6",
    firstName: "Olivia",
    lastName: "Firestorm",
    phoneNumber: "0868765432",
    email: "olivia_fire@gmail.com",
    group: "Zeta",
    level: "Level 3",
    status: "Offline",
    erpStatus: "Deactivated",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Iceberg",
    phoneNumber: "0871234567",
    email: "david_ice@gmail.com",
    group: "Eta",
    level: "Level 4",
    status: "Online",
    erpStatus: "Activated",
  },
  {
    id: "8",
    firstName: "Sophia",
    lastName: "Stormrider",
    phoneNumber: "0887654321",
    email: "sophia_storm@gmail.com",
    group: "Theta",
    level: "Level 2",
    status: "Offline",
    erpStatus: "Deactivated",
  },
  {
    id: "9",
    firstName: "William",
    lastName: "Lightning",
    phoneNumber: "0892345678",
    email: "william_light@gmail.com",
    group: "Iota",
    level: "Level 1",
    status: "Online",
    erpStatus: "Activated",
  },
  {
    id: "10",
    firstName: "Ava",
    lastName: "Nightshade",
    phoneNumber: "0909876543",
    email: "ava_night@gmail.com",
    group: "Kappa",
    level: "Level 5",
    status: "Offline",
    erpStatus: "Deactivated",
  },
];

export const memoData = [
  {
    id: "1",
    title: "The world moon",
    summary: "The ending part of the world is like the light of the moon.",
    approvers: ["john doe", "mark loe"],
    date: "11/11/2023",
    status: "Processing",
  },
  {
    id: "2",
    title: "Ocean's Embrace",
    summary: "Beneath the waves, secrets unfold like a dance of reflections.",
    approvers: ["mary smith", "alex brown"],
    date: "12/01/2023",
    status: "Pending",
  },
  {
    id: "3",
    title: "Eternal Flames",
    summary: "In the heart of chaos, flames of resilience burn eternally.",
    approvers: ["jane roe", "peter green"],
    date: "12/05/2023",
    status: "Approved",
  },
  {
    id: "4",
    title: "Whispers in the Wind",
    summary: "Secrets are carried away by the wind's gentle whispers.",
    approvers: ["chris black", "susan white"],
    date: "12/10/2023",
    status: "Rejected",
  },
  {
    id: "5",
    title: "City of Dreams",
    summary: "Skyscrapers stand tall, reflecting the dreams of millions.",
    approvers: ["michael grey", "emily stone"],
    date: "12/15/2023",
    status: "Processing",
  },
  {
    id: "6",
    title: "Silent Symphony",
    summary: "In the stillness, nature conducts a silent symphony of life.",
    approvers: ["lisa adams", "david lee"],
    date: "12/20/2023",
    status: "Pending",
  },
  {
    id: "7",
    title: "Lost Horizons",
    summary: "Beyond the horizon, the unknown beckons with promises untold.",
    approvers: ["steve miller", "olivia jones"],
    date: "12/25/2023",
    status: "Approved",
  },
  {
    id: "8",
    title: "Whimsical Wonderland",
    summary:
      "A fantastical realm where imagination takes flight on wings of wonder.",
    approvers: ["alice carter", "samuel hill"],
    date: "12/30/2023",
    status: "Rejected",
  },
  {
    id: "9",
    title: "Mystical Meadows",
    summary:
      "In the meadows, magic blooms with the colors of a thousand dreams.",
    approvers: ["grace evans", "robert cole"],
    date: "01/05/2024",
    status: "Processing",
  },
  {
    id: "10",
    title: "Timeless Tapestry",
    summary:
      "Threads of time weave a tapestry that tells the story of eternity.",
    approvers: ["brandon king", "natalie ford"],
    date: "01/10/2024",
    status: "Pending",
  },
];
