export const meritOptions = [
  "Employee of the Month",
  "Outstanding Customer Service",
  "Leadership Excellence",
  "Diversity Champion",
  "High-Profile Project Completion",
  "Sales Target Achievement",
  "Innovation Award",
  "Community Project Contribution",
  "Years of Service Milestone",
  "Professional Certifications",
  "High-Value Client Praise",
  "KPI Achievement",
  "Perfect Attendance",
  "Cost-Saving Contribution",
  "Culture Enhancement",
  "New Process Implementation",
  "Personal Goal Achievement",
  "Peer Recognition",
  "Team-Building Contribution",
  "Crisis Management Excellence",
];
